# Generated by Django 5.2.11 on 2026-02-25 20:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Код"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "icon",
                    models.CharField(default="🏆", max_length=50, verbose_name="Иконка"),
                ),
                (
                    "condition_type",
                    models.CharField(
                        help_text="total_sessions, correct_answers, streak, etc.",
                        max_length=50,
                        verbose_name="Тип условия",
                    ),
                ),
                (
                    "condition_value",
                    models.IntegerField(verbose_name="Значение условия"),
                ),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "value",
                    models.IntegerField(default=1, verbose_name="Числовое значение"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "color",
                    models.CharField(
                        default="green", max_length=20, verbose_name="Цвет в интерфейсе"
                    ),
                ),
            ],
            options={
                "verbose_name": "Уровень сложности",
                "verbose_name_plural": "Уровни сложности",
            },
        ),
        migrations.CreateModel(
            name="ExerciseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Код (для API)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "icon",
                    models.CharField(default="🎵", max_length=50, verbose_name="Иконка"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
            ],
            options={
                "verbose_name": "Тип упражнения",
                "verbose_name_plural": "Типы упражнений",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "experience_points",
                    models.IntegerField(default=0, verbose_name="Опыт"),
                ),
                (
                    "daily_goal",
                    models.IntegerField(
                        default=10, verbose_name="Дневная цель (упражнений)"
                    ),
                ),
                (
                    "avatar",
                    models.URLField(blank=True, null=True, verbose_name="Аватар"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, max_length=500, verbose_name="О себе"),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="Премиум доступ"),
                ),
                (
                    "last_active",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Последняя активность",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название конфигурации"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Пример для нот: {"min_octave": 2, "max_octave": 5, "notes": ["C", "D", "E", "F", "G", "A", "B"]}\n        Для интервалов: {"min_interval": 1, "max_interval": 8, "quality": ["major", "minor", "perfect"]}\n        Для аккордов: {"chord_types": ["major", "minor", "diminished", "augmented"]}\n        ',
                        verbose_name="Настройки",
                    ),
                ),
                (
                    "questions_per_session",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Вопросов за сессию",
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="0 = без ограничения",
                        verbose_name="Лимит времени",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный доступ"),
                ),
                (
                    "times_used",
                    models.IntegerField(
                        default=0, verbose_name="Количество использований"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "difficulty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configs",
                        to="api.difficultylevel",
                        verbose_name="Сложность",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лайки",
                    ),
                ),
                (
                    "exercise_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="api.exercisetype",
                        verbose_name="Тип упражнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфигурация упражнения",
                "verbose_name_plural": "Конфигурации упражнений",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("abandoned", "Брошено"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начало"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение"
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="Всего вопросов"),
                ),
                (
                    "answered_questions",
                    models.IntegerField(default=0, verbose_name="Отвечено"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="Правильных"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="api.exerciseconfig",
                        verbose_name="Конфигурация",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия упражнения",
                "verbose_name_plural": "Сессии упражнений",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_data",
                    models.JSONField(
                        help_text="Содержит ноты, интервалы и т.д.",
                        verbose_name="Данные вопроса",
                    ),
                ),
                ("correct_answer", models.JSONField(verbose_name="Правильный ответ")),
                (
                    "user_answer",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Ответ пользователя"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Правильно?"
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(default=0, verbose_name="Время на ответ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время ответа"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.exercisesession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получено"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.achievement",
                        verbose_name="Достижение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достижение пользователя",
                "verbose_name_plural": "Достижения пользователей",
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_key",
                    models.CharField(max_length=50, verbose_name="Ключ элемента"),
                ),
                (
                    "element_name",
                    models.CharField(max_length=100, verbose_name="Название элемента"),
                ),
                (
                    "total_attempts",
                    models.IntegerField(default=0, verbose_name="Всего попыток"),
                ),
                (
                    "correct_attempts",
                    models.IntegerField(default=0, verbose_name="Правильных"),
                ),
                (
                    "last_attempted",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последняя попытка"
                    ),
                ),
                (
                    "mastery_level",
                    models.FloatField(
                        default=0.0,
                        help_text="0.0 - 1.0",
                        verbose_name="Уровень освоения",
                    ),
                ),
                (
                    "next_review_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата следующего повторения",
                    ),
                ),
                (
                    "exercise_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.exercisetype",
                        verbose_name="Тип упражнения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя",
                "verbose_name_plural": "Прогресс пользователей",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="api_user_usernam_edfd3a_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="api_user_email_a7eefd_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["level"], name="api_user_level_678b4a_idx"),
        ),
        migrations.AddIndex(
            model_name="exercisesession",
            index=models.Index(
                fields=["user", "status"], name="api_exercis_user_id_817cc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercisesession",
            index=models.Index(
                fields=["started_at"], name="api_exercis_started_5a4e22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exerciseconfig",
            index=models.Index(
                fields=["created_at"], name="api_exercis_created_9969b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exerciseconfig",
            index=models.Index(
                fields=["is_public"], name="api_exercis_is_publ_e06985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exerciseconfig",
            index=models.Index(
                fields=["exercise_type", "difficulty"],
                name="api_exercis_exercis_48f57e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["session", "is_correct"], name="api_questio_session_664a02_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together={("user", "achievement")},
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "mastery_level"], name="api_userpro_user_id_d96fcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["next_review_date"], name="api_userpro_next_re_cf94bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "exercise_type", "element_key")},
        ),
    ]
