# Generated by Django 5.2.11 on 2026-02-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisetype",
            name="code",
            field=models.CharField(
                default="migration_temp",
                max_length=20,
                unique=True,
                verbose_name="Код (для API)",
            ),
            preserve_default=False,
        ),
    ]
