# Generated by Django 5.2.13 on 2026-04-08 08:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='difficultylevel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exerciseconfig',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='exercisesession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exercisetype',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='exerciseconfig',
            name='api_exercis_created_9969b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='exerciseconfig',
            name='api_exercis_is_publ_e06985_idx',
        ),
        migrations.RemoveIndex(
            model_name='exerciseconfig',
            name='api_exercis_exercis_48f57e_idx',
        ),
        migrations.RemoveIndex(
            model_name='exercisesession',
            name='api_exercis_user_id_817cc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='exercisesession',
            name='api_exercis_started_5a4e22_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='api_questio_session_664a02_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprogress',
            name='api_userpro_user_id_d96fcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprogress',
            name='api_userpro_next_re_cf94bd_idx',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='🏆', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='color',
            field=models.CharField(default='green', max_length=20),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='difficultylevel',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configs', to='api.difficultylevel'),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_configs', to='api.exercisetype'),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='questions_per_session',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='time_limit_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='answered_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.exerciseconfig'),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершено'), ('abandoned', 'Брошено')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercisesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='icon',
            field=models.CharField(default='🎵', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.exercisesession'),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_spent_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_goal',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='correct_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='element_key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='element_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='exercise_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='api.exercisetype'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_attempted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='mastery_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='next_review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
