# Generated by Django 5.2.13 on 2026-04-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseconfig',
            name='exercise_types',
            field=models.ManyToManyField(related_name='configs', to='api.exercisetype'),
        ),
        migrations.AddField(
            model_name='exerciseconfig',
            name='type_settings',
            field=models.JSONField(default=dict, help_text='Настройки для каждого типа'),
        ),
        migrations.AlterField(
            model_name='exerciseconfig',
            name='exercise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_configs', to='api.exercisetype'),
        ),
    ]
