# Generated by Django 5.2.13 on 2026-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exerciseconfig_exercise_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesession',
            name='last_element_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
