# Generated by Django 5.2.13 on 2026-04-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adaptive_mode',
            field=models.BooleanField(default=True, verbose_name='Адаптивный режим'),
        ),
    ]
