version: "3.9"

services:

  db:
    image: postgres:15
    container_name: music_postgres
    environment:
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: music_app_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music_user -d music_app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: music_backend
    command: >
      sh -c "python wait-for-db.py &&
             python manage.py migrate &&
             gunicorn backend_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: music_app_db
      DB_USER: music_user
      DB_PASSWORD: supersecret
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: music_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: