name: CI

on:
  push:
    branches: [ labwork5, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Backend
        run: docker build -t music-backend ./backend
        
      - name: Build Frontend
        run: docker build -t music-frontend ./frontend
      
      - name: Start containers
        run: |
          docker-compose up -d
          sleep 15
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Run Postman tests
        run: newman run postman/collection.json
      
      - name: Stop containers
        run: docker-compose down